use_frameworks!

platform :ios, '8.0'

target 'ZYExtension_Example' do
  pod 'ZYExtension', :path => '../'

  target 'ZYExtension_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
